module SyncApp {
  interface SyncCallback {
    oneway void callback(in long random);
  };

  interface Sync {
    oneway void getRandomNumberAsync(in SyncCallback ref);
    long getRandomNumber();
  };
};
