package HelloApp;

/**
* HelloApp/HelloAppHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* Tuesday, 13 October 2015 1:01:09 PM AEDT
*/

public final class HelloAppHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.HelloApp value = null;

  public HelloAppHolder ()
  {
  }

  public HelloAppHolder (HelloApp.HelloApp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.HelloAppHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.HelloAppHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.HelloAppHelper.type ();
  }

}
