package HelloApp;


/**
* HelloApp/HelloAppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* Tuesday, 13 October 2015 1:01:09 PM AEDT
*/

public interface HelloAppOperations 
{
  String sayHello ();
} // interface HelloAppOperations
